language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: UH0tDPxmrJOK9oxuO37LwVbzY1MODzndeptEt8JL7JiEk0AOBXqIgYwwK3tUggR4cKNqDhAQh3sqrbqfiixYP4bnhN9KzSWnPPiZjUg2LhTbhbRvruVRE9VYbp7IjhD7f1ZR2uu79q+tk9m8URzIJqOCaaMYQQEEwcl5Mwf0NlALKgB1m+qxm7Xyw4lU9xTK8oDJxzdldK3TtCL+q2GkJJI6Dz7TiFk2ECmVjTF5EcFQtLuhEIUuPzT5xTMaaPlW57o0TgkSTtq27zxhmsRGf4rE4Kn8Xm8s1/eAW4jL6x+KUM0O6ncK/TmyfWAqEMAaBCnVUJodpn7OVZCy50skjximIqEFsnFSd9U0LHmcYF3LQr/gMHr4KtrBN8UlGKOFUMIu6mneF5WEprBCV7LQsHNhvHoe5r3VcRq2WXHBpI5G6V9FvD3FyNkVsdlDNXwyLqZL3miq6WsLVQPnR8NqDQzWV0DMTc+TILb6LgjByD6po1kwQsAh7YQHt6ZETopACziESWW2xF+P2N+RoEa9VZWIZlJ4BxlNPPvABEAdxpMaMNLncqYI4y4DD5qNuANudKO/Yv4Bbx/I14EevUC1DcJKwuJjkufJyVZmoM6qtLv1UAEgZo9d1sHKBSXuh8JBy0MNFDGswRyT3xe/3+fhnTcbMz/YvzxXmPQvZuZ1FGA=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
